I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 324, in script
    scene bg hall with dissolve(2.0)
TypeError: 'Dissolve' object is not callable

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 324, in script
    scene bg hall with dissolve(2.0)
  File "C:\PythonPrograms\renpy-7.3.5-sdk\renpy\ast.py", line 1389, in execute
    renpy.exports.with_statement(trans, paired)
  File "C:\PythonPrograms\renpy-7.3.5-sdk\renpy\exports.py", line 1601, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "C:\PythonPrograms\renpy-7.3.5-sdk\renpy\display\core.py", line 2251, in do_with
    clear=clear)
  File "C:\PythonPrograms\renpy-7.3.5-sdk\renpy\display\core.py", line 2702, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, **kwargs)
  File "C:\PythonPrograms\renpy-7.3.5-sdk\renpy\display\core.py", line 3047, in interact_core
    new_widget=layers_root)
TypeError: 'Dissolve' object is not callable

Windows-8-6.2.9200
Ren'Py 7.3.5.606
eldrazi_sim 1.0
Thu Mar 04 23:44:22 2021
